# Generated by Django 4.0 on 2021-12-11 10:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_delete_user_alter_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2021, 12, 11, 10, 29, 56, 594309, tzinfo=utc), max_length=250),
            preserve_default=False,
        ),
    ]
